In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
b = np.array([[1,2],
              [3,4],
              [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((3,4))

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [22]:
c.shape, c.ndim, c.dtype

((3, 4), 2, dtype('float64'))

Exercise 1 (quick)

- Make a 3×3 array of all 7s
- Make numbers 1..12 and reshape to (3,4)

In [25]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [29]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
x = np.array([10,20,30,40,50])
x, x[0], x[-2]

(array([10, 20, 30, 40, 50]), 10, 40)

In [40]:
# x[begin:end]

x [:3]

array([10, 20, 30])

In [53]:
x = np.array([[1,2,3,55,56,57],
             [4,5,6,66,67,68],
             [7,8,9,99,96,97],
             [33,44,50,23,45,23]])
x

array([[ 1,  2,  3, 55, 56, 57],
       [ 4,  5,  6, 66, 67, 68],
       [ 7,  8,  9, 99, 96, 97],
       [33, 44, 50, 23, 45, 23]])

In [54]:
# x[row[b:e] , col[b:e]]

x[1,1], x[1,2]

(5, 6)

In [56]:
x[1, 1:3]

array([5, 6])

In [57]:
x[1:3, 1:3]

array([[5, 6],
       [8, 9]])